# This file was generated by GoReleaser. DO NOT EDIT.
cask "yggdrasil" do
  version "0.1.14"

  on_macos do
    on_arm do
      sha256 "91d5f2d9a5c20acd6098c3ef5074e921ef68aa85b920ee9f30f065c162a99647"
      url "https://github.com/Simpliphy-Inc/homebrew-tap/releases/download/v#{version}/yggdrasil_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "yggdrasil"
  desc "Manage many local git worktrees per canonical repo."
  homepage "https://github.com/Simpliphy-Inc/yggdrasil"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yggdrasil"

  # No zap stanza required

end
