# This file was generated by GoReleaser. DO NOT EDIT.
cask "yggdrasil" do
  version "0.1.21"

  on_macos do
    on_arm do
      sha256 "96cc1a093905bce61a0aa6a06f970d167f258abbd9d204734db5eeac0da31ef5"
      url "https://github.com/Simpliphy-Inc/homebrew-tap/releases/download/v#{version}/yggdrasil_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "yggdrasil"
  desc "Manage many local git worktrees per canonical repo."
  homepage "https://github.com/Simpliphy-Inc/yggdrasil"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yggdrasil"

  # No zap stanza required

end
