# This file was generated by GoReleaser. DO NOT EDIT.
cask "yggdrasil" do
  version "0.1.29"

  on_macos do
    on_arm do
      sha256 "2cac6b160035fa3c7a2bc4f969ec3ba5087b39703ec8608e54b2afaf8268fec6"
      url "https://github.com/Simpliphy-Inc/homebrew-tap/releases/download/v#{version}/yggdrasil_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "yggdrasil"
  desc "Manage many local git worktrees per canonical repo."
  homepage "https://github.com/Simpliphy-Inc/yggdrasil"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yggdrasil"

  # No zap stanza required

end
